### ISSUE TITLE
안녕하세요 한가지 궁금한게 있어서 질문드립니다

### ISSUE THREAD

**Issue by donghwan92** [solaris33/deep-learning-tensorflow-book-code#1]
안녕하세요 semantic segmentation을 하려고 책을 구매하여 책에 있는 FCN8s 코드를 돌려보던 중 코드에 자꾸 오류가 뜹니다 ㅜㅜ

VGG 모델과 ADEChallengeData2016.zip 파일까지는 받아지는데 그 이후에 ADEChallengeData2016.zip 에서 압축해제된 사진 파일들이 읽히지가 않습니다 ㅜㅜ
Annotation file not found for ADEChallengeData2016\images\training\ADE_train_00000001 - Skipping << 라는 식으로 자꾸 뜨고.... 해당 폴더에 사진들이 있는데도 자꾸 이런 문구가 뜨면서 학습이 진행이 안됩니다.

파이썬에 대한 지식이 많지는 않지만 아마 read_MITSceneParsingData.py 코드가 잘못된거 같다라는 생각이 듭니다.. 답변해주시면 감사하겠습니다

**Comment by solaris33** [comment]
안녕하세요.

첨부해주신 에러메세지를 보면 윈도우 환경에서 작업중이신 것 같은데요.

윈도우 환경에서는

https://github.com/solaris33/deep-learning-tensorflow-book-code/blob/master/Ch10-Semantic_Image_Segmentation/FCN.tensorflow/read_MITSceneParsingData.py#L58

파일에서 58번째 라인을 아래와 같이 변경하고 돌려보시기 바랍니다.

```
filename = os.path.splitext(f.split("/")[-1])[0]
->
filename = os.path.splitext(f.split("\\")[-1])[0]
```

감사합니다.
