### ISSUE TITLE
ValueError: Cannot feed value of shape (0,) for Tensor 'input_image:0', which has shape '(?, 224, 224, 3)'

### ISSUE THREAD

**Issue by SeunghwanByun** [solaris33/deep-learning-tensorflow-book-code#2]
코드를 다 작성하고 실행을 시켰더니 이런 에러가 나타납니다.
환경은 windows 10에서 Pycharm으로 작업을 하고 있습니다만.. 구글링을 해보니 윈도우에서는 데이터 경로를 적어줄 때 '/'가 아니라 '\\'로 적으라고 하더군요. 그런데 그렇게 고쳐보아도 고쳐지지 않습니다. 어떻게 해결해야하죠..?

**Comment by solaris33** [comment]
안녕하세요. #1 과 같은 상황이신것 같은데요.

윈도우 환경에서는

https://github.com/solaris33/deep-learning-tensorflow-book-code/blob/master/Ch10-Semantic_Image_Segmentation/FCN.tensorflow/read_MITSceneParsingData.py#L58

파일에서 58번째 라인을 아래와 같이 변경하고 돌려보시기 바랍니다.

```
filename = os.path.splitext(f.split("/")[-1])[0]
->
filename = os.path.splitext(f.split("\\")[-1])[0]
```

감사합니다.
