### ISSUE TITLE
안녕하세요 BatchDatsetReader.py에 대해 질문 드립니다.

### ISSUE THREAD

**Issue by younkipark** [solaris33/deep-learning-tensorflow-book-code#5]
해당 코드에 사용 된 scipy.misc.imresize의 경우 scipy 1.3이상 버전에선 작동이 되지 않아 

resize_image = misc.imresize(image, [resize_size, resize_size], interp='nearest') 를

resize_image = np.array(Image.fromarray(image).resize([resize_size, resize_size]))
그리고
resize_image = cv2.resize(image, dsize=(resize_size, resize_size), interpolation=cv2.INTER_NEAREST)를 통해서도 적용해 보았는데도 실행이 되지 않았습니다.

혹시 scipy.misc 말고 다른 방법으로 이미지에 변형을 가하는 방법이 있을 까요?

또 해당 코드를 작성하였을 때 기준으로 numpy, tensorflow등 import된 라이브러리들의 버전 사양이 어떻게 되는 건지도 알 수 있을 까요?

**Comment by solaris33** [comment]
안녕하세요. 최신버전의 scipy에 호환되게 BatchDatsetReader.py 파일을 수정한 아래 gist 코드를 사용하시길 바랍니다.

https://gist.github.com/solaris33/2805ce8df807096fde82a4f68ddffdef

감사합니다.
